# Generated by Django 4.1.2 on 2022-10-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=240, null=True)),
                ('displayed_url', models.CharField(blank=True, max_length=240, null=True)),
                ('description', models.TextField()),
                ('extra_info', models.CharField(blank=True, max_length=240, null=True)),
                ('position', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('app', models.CharField(blank=True, max_length=240, null=True)),
                ('query', models.CharField(blank=True, max_length=240, null=True)),
                ('violator_url', models.CharField(blank=True, max_length=240, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
